name: Atualizar Link

on:
  push:
    branches:
      - main  # ou a branch principal do seu repositório

jobs:
  update-link:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Generate link
      run: |
        echo "https://github.com/vihh-ketelly/repoo3" > link.txt
        git add link.txt
        git commit -m "Atualizar link automaticamente"
        git push
